<a href="https://colab.research.google.com/github/JoyceQuintino/DataScienceAlgorithms/blob/master/Seminario_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Variáveis

In [ ]:
a = 10
b = 'Joyce'

In [ ]:
print('O valor da primeira é', a, 'O valor da segunda é', b)

O valor da primeira é 10 O valor da segunda é Joyce


In [ ]:
#Operadores Aritméticos

In [ ]:
c = 20

In [ ]:
#Operadores de Comparação

In [ ]:
num = 2

In [ ]:
num == 2 

True

In [ ]:
num != 2

False

In [ ]:
num <= 3

True

In [ ]:
num >= 3

False

In [ ]:
#Operadores Lógicos

In [ ]:
verdade = True
mentira = False

In [ ]:
verdade and not mentira 

True

In [ ]:
not verdade and mentira

False

In [ ]:
#Condicionais

In [ ]:
# if, else, elif

In [ ]:
if num > 1:
  print('ok')
elif num < 1:
  print('ok2')

ok


In [ ]:
#for, while

In [ ]:
num = [1,2,3] 

for i in num:
  print(i)

1
2
3


In [ ]:
count = 0

while(count < 4):
  print('Ola')
  count += 1

Ola
Ola
Ola
Ola


In [ ]:
#Tuplas 
#Listas
#Dicionários

In [ ]:
#Numpy
import numpy as np

my_array = np.array([3, 4, 5])
my_array[1]

4

In [ ]:
#Slicing
my_array[1:3]

array([4, 5])

In [ ]:
array_gerado = np.arange(1,14)
array_gerado

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
array_gerado[1:5]

array([2, 3, 4, 5])

In [ ]:
#Faz o cálculo da média final e diz se o aluno foi aprovado, ficou de recuperação ou foi reprovado
def media_final(notas):
  soma = 0
  for n in notas:
    soma += n
  media = soma / len(notas)
  media = round(media, 2)

  if media >= 7:
    situacao = 'Aprovado'
  elif media >= 6 and media < 7:
    situacao = 'Recuperação'
  else:
    situacao = 'Reprovado'
  return [media, situacao]

In [ ]:
notas = []
alunos = []
medias = []
situacoes = []
dic_alunos_aux = {}
media_alunos = {}

count = 0
num = int(input('Digite a quantidade de alunos para cálculo da média:'))

while(count < num):
  aluno = input('Digite o nome do aluno:')
  for i in range(0, 4):
    notas.append(float(input('Digite sua nota {j}: '.format(j=i+1))))
  dic_alunos_aux[count+1] = aluno, notas
  resultado = media_final(notas)
  alunos.append(aluno)
  medias.append(resultado[0])
  situacoes.append(resultado[1])
  notas = []
  count += 1

relatorio = {
    'Nome do aluno': alunos,
    'Média final': medias,
    'Situação do aluno': situacoes
}

Digite a quantidade de alunos para cálculo da média:1
Digite o nome do aluno:joyce
Digite sua nota 1: 10
Digite sua nota 2: 10
Digite sua nota 3: 10
Digite sua nota 4: 10


In [ ]:
relatorio

{'Média final': [10.0],
 'Nome do aluno': ['joyce'],
 'Situação do aluno': ['Aprovado']}

In [ ]:
import pandas as pd

#Transforma o dicionário de relatório em um dataframe 
pd.DataFrame(relatorio)

Nome do aluno  Média final Situação do aluno
0         joyce         10.0          Aprovado